### ISSUE TITLE
[Build Error] Nothing happens with Debian 11

### ISSUE THREAD

**Issue by DavidGriffith** [lencx/ChatGPT#348]
### Error message

Build instructions are very cryptic.  There seems to be something missing from the build instructions.

````
$ git clone git@github.com:lencx/ChatGPT.git
...
$ cd ChatGPT
$ yarn
00h00m00s 0/0: : ERROR: There are no scenarios; must have at least one.
$ yarn dev
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'dev'
$ mkdir dev
$ yarn dev
00h00m00s 0/0: : ERROR: [Errno 21] Is a directory: 'dev'
$ yarn build
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'build'
$ mkdir build
$ yarn build
00h00m00s 0/0: : ERROR: [Errno 21] Is a directory: 'build'
````

### OS

Debian 11

**Comment by yixinBC** [comment]
Please provide your `yarn` version and reconfirm that you have cloned the complete project.

**Comment by Manamama** [comment]
Your yarn looks kinda funny. 
I have tested it on a virgin Ubuntu (github spaces) box, see specs below, out of sheer curiosity, and : 
`git clone https://github.com/lencx/ChatGPT/`
and then:
```
 yarn
yarn install v1.22.19
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
warning tsconfck@2.0.2: The engine "pnpm" appears to be invalid.
[3/4] Linking dependencies...
warning " > @monaco-editor/react@4.4.6" has unmet peer dependency "monaco-editor@>= 0.25.0 < 1".
warning "@monaco-editor/react > @monaco-editor/loader@1.3.2" has unmet peer dependency "monaco-editor@>= 0.21.0 < 1".
[4/4] Building fresh packages...
success Saved lockfile.
$ husky install
husky - Git hooks installed
Done in 69.80s.
```

but then indeed:
```
yarn dev
yarn run v1.22.19
$ yarn tauri dev
$ tauri dev
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/interface/rust.rs:762:69
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Done in 1.82s.
```

plus:
```
yarn dev RUST_BACKTRACE=1
yarn run v1.22.19
$ yarn tauri dev RUST_BACKTRACE=1
$ tauri dev RUST_BACKTRACE=1
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/interface/rust.rs:762:69
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Done in 1.59s.

```

> 
> --------------------------- 
> OS: Ubuntu 20.04.5 LTS x86_64 
> Host: Virtual Machine 7.0 
> Kernel: 5.4.0-1101-azure 
> Uptime: 25 mins 
> Packages: 1646 (dpkg) 
> Shell: bash 5.0.17 
> Terminal: /dev/pts/0 
> CPU: Intel Xeon Platinum 8272CL (4) @ 2.593GHz 
> GPU: 00:08.0 Microsoft Corporation Hyper-V virtual VGA 
> Memory: 640MiB / 7957MiB

**Comment by Manamama** [comment]
Indeed, something is missing there:
`src/interface/rust.rs in line 762`
 so just quick FYI:
```
@Manamama ➜ ~/Downloads $ cd ChatGPT/
@Manamama ➜ ~/Downloads/ChatGPT (main) $ find src/ -name rust.rs
@Manamama ➜ ~/Downloads/ChatGPT (main) $ find  -name rust.rs
@Manamama ➜ ~/Downloads/ChatGPT (main) $ grep -r 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }' src/
@Manamama ➜ ~/Downloads/ChatGPT (main) $ grep -r 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }' 
```

- still zilch.

**Comment by Manamama** [comment]
Indeed, something is missing there:
`src/interface/rust.rs in line 762`
 so just quick FYI:
```
@Manamama ➜ ~/Downloads $ cd ChatGPT/
@Manamama ➜ ~/Downloads/ChatGPT (main) $ find src/ -name rust.rs
@Manamama ➜ ~/Downloads/ChatGPT (main) $ find  -name rust.rs
@Manamama ➜ ~/Downloads/ChatGPT (main) $ grep -r 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }' src/
@Manamama ➜ ~/Downloads/ChatGPT (main) $ grep -r 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }' 
```

- still zilch.

**Comment by boozedog** [comment]
I'm having similar problem:

```
% yarn dev    
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/interface/rust.rs:762:69
```

**Comment by Manamama** [comment]
@boozedog so it is reproducible. Try updating your yarn (see above) and tell us what you get.

**Comment by boozedog** [comment]
> @boozedog so it is reproducible. Try updating your yarn (see above) and tell us what you get.

I was using yarn 3.4.1

```
% yarn --version
3.4.1
```

**Comment by lifenglsf** [comment]
do you have install rust
