### ISSUE TITLE
[Build Error] error when starting dev server: Error: Cannot find module 'node:path'

### ISSUE THREAD

**Issue by mrdulin** [lencx/ChatGPT#463]
### Error message

```bash
⚡  npm run dev:fe 

> chatgpt@0.0.0 dev:fe
> vite

failed to load config from /Users/dulin/workspace/github.com/mrdulin/ChatGPT/vite.config.ts
error when starting dev server:
Error: Cannot find module 'node:path'
Require stack:
- /Users/dulin/workspace/github.com/mrdulin/ChatGPT/node_modules/.pnpm/vite@4.1.1_w4o4wsgkler5i3zieyqxrswv2u/node_modules/vite/dist/node-cjs/publicUtils.cjs
- /Users/dulin/workspace/github.com/mrdulin/ChatGPT/node_modules/.pnpm/vite@4.1.1_w4o4wsgkler5i3zieyqxrswv2u/node_modules/vite/index.cjs
- /Users/dulin/workspace/github.com/mrdulin/ChatGPT/vite.config.ts
- /Users/dulin/workspace/github.com/mrdulin/ChatGPT/node_modules/.pnpm/vite@4.1.1_w4o4wsgkler5i3zieyqxrswv2u/node_modules/vite/dist/node/chunks/dep-3007b26d.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/Users/dulin/workspace/github.com/mrdulin/ChatGPT/node_modules/.pnpm/vite@4.1.1_w4o4wsgkler5i3zieyqxrswv2u/node_modules/vite/dist/node-cjs/publicUtils.cjs:3:14)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Object._require.extensions.<computed> [as .js] (file:///Users/dulin/workspace/github.com/mrdulin/ChatGPT/node_modules/.pnpm/vite@4.1.1_w4o4wsgkler5i3zieyqxrswv2u/node_modules/vite/dist/node/chunks/dep-3007b26d.js:62324:17)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
```

### OS

MacOS 10.15.7 (19H2026)

### Environment

The issue caused by the Node.js version, the `node:` import is supported in  v16.0.0+, v14.18.0+. See https://nodejs.org/api/esm.html#node-imports

Solution: 

Use the "engines" field in `package.json` to specify which versions of npm are capable of properly installing your program. see  https://docs.npmjs.com/cli/v9/configuring-npm/package-json#engines 

> Unless the user has set the [engine-strict config](https://docs.npmjs.com/cli/v9/using-npm/config#engine-strict) flag, this field is advisory only and will only produce warnings when your package is installed as a dependency.

See https://pnpm.io/npmrc#engine-strict

> If this is enabled, pnpm will not install any package that claims to not be compatible with the current Node version.

> Regardless of this configuration, installation will always fail if a project (not a dependency) specifies an incompatible version in its engines field.

**Comment by mrdulin** [comment]
[PR](https://github.com/lencx/ChatGPT/pull/464)
