### ISSUE TITLE
[Bug] Not running.

### ISSUE THREAD

**Issue by arthurwolf** [lencx/ChatGPT#518]
### Version

latest, downloaded this instant

### Bug description

I tried multiple ways of running it, and all of them fail.

.deb:

```
╭─arthur at aquarelle in ~/Downloads/ChatGPT on main✘✘✘ 23-02-27 - 15:04:31
╰─⠠⠵ chat-gpt                                                                                                                                                        on main|…1
chat-gpt: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
```

Appimage:

```
╭─arthur at aquarelle in ~/Downloads 23-02-27 - 15:05:26
╰─○ ./chat-gpt_0.11.0_amd64.AppImage
chat-gpt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by chat-gpt)
chat-gpt: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /tmp/.mount_chat-gkzNFFK/usr/lib/libwebkit2gtk-4.0.so.37)
chat-gpt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_chat-gkzNFFK/usr/lib/libwebkit2gtk-4.0.so.37)
chat-gpt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_chat-gkzNFFK/usr/lib/libgdk-3.so.0)
chat-gpt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_chat-gkzNFFK/usr/lib/libcairo.so.2)
chat-gpt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_chat-gkzNFFK/usr/lib/libgio-2.0.so.0)
chat-gpt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_chat-gkzNFFK/usr/lib/libjavascriptcoregtk-4.0.so.18)
chat-gpt: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /tmp/.mount_chat-gkzNFFK/usr/lib/libjavascriptcoregtk-4.0.so.18)
chat-gpt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_chat-gkzNFFK/usr/lib/libglib-2.0.so.0)
chat-gpt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_chat-gkzNFFK/usr/lib/libdbus-1.so.3)
chat-gpt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_chat-gkzNFFK/usr/lib/libcrypto.so.3)
chat-gpt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_chat-gkzNFFK/usr/lib/libicuuc.so.70)
chat-gpt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_chat-gkzNFFK/usr/lib/libsystemd.so.0)
chat-gpt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_chat-gkzNFFK/usr/lib/libxml2.so.2)
chat-gpt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_chat-gkzNFFK/usr/lib/libsqlite3.so.0)
chat-gpt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_chat-gkzNFFK/usr/lib/libgstreamer-1.0.so.0)
chat-gpt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_chat-gkzNFFK/usr/lib/libopenjp2.so.7)
chat-gpt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_chat-gkzNFFK/usr/lib/libwebp.so.7)
chat-gpt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_chat-gkzNFFK/usr/lib/libgmodule-2.0.so.0)
chat-gpt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_chat-gkzNFFK/usr/lib/libwayland-server.so.0)
chat-gpt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_chat-gkzNFFK/usr/lib/libepoxy.so.0)
chat-gpt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_chat-gkzNFFK/usr/lib/libmount.so.1)
chat-gpt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_chat-gkzNFFK/usr/lib/libselinux.so.1)
chat-gpt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_chat-gkzNFFK/usr/lib/liblzma.so.5)
chat-gpt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_chat-gkzNFFK/usr/lib/libunwind.so.8)
chat-gpt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_chat-gkzNFFK/usr/lib/libdw.so.1)
chat-gpt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_chat-gkzNFFK/usr/lib/libudev.so.1)
chat-gpt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_chat-gkzNFFK/usr/lib/libunistring.so.2)
chat-gpt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_chat-gkzNFFK/usr/lib/libkrb5.so.3)
chat-gpt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_chat-gkzNFFK/usr/lib/libkrb5support.so.0)
```

git checkout then yarn dev:

```
╭─arthur at aquarelle in ~/Downloads/ChatGPT on main✘✘✘ 23-02-27 - 15:05:51
╰─⠠⠵ yarn dev                                                                                                                                                        on main|…1
yarn run v1.22.19
$ tauri dev
     Running BeforeDevCommand (`npm run dev:fe`)

> chatgpt@0.0.0 dev:fe
> vite


  VITE v4.1.4  ready in 491 ms

  ➜  Local:   http://localhost:1420/
  ➜  Network: use --host to expose
        Info Watching /home/arthur/Downloads/ChatGPT/src-tauri for changes...
error: no matching package named `tauri-plugin-autostart` found
location searched: https://github.com/lencx/tauri-plugins-workspace?branch=dev#bf1106a0
required by package `chatgpt v0.0.0 (/home/arthur/Downloads/ChatGPT/src-tauri)`
Terminated
/home/arthur/Downloads/ChatGPT/node_modules/esbuild/lib/main.js:1145
        return callback(new Error(error), null);
                        ^

Error: The service was stopped: write EPIPE
    at /home/arthur/Downloads/ChatGPT/node_modules/esbuild/lib/main.js:1145:25
    at Object.responseCallbacks.<computed> (/home/arthur/Downloads/ChatGPT/node_modules/esbuild/lib/main.js:701:9)
    at afterClose (/home/arthur/Downloads/ChatGPT/node_modules/esbuild/lib/main.js:691:28)
    at /home/arthur/Downloads/ChatGPT/node_modules/esbuild/lib/main.js:2097:11
    at onwriteError (node:internal/streams/writable:417:3)
    at processTicksAndRejections (node:internal/process/task_queues:85:21)
error Command failed with exit code 101.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

How do I fix this, what should I do?

### OS

Ubuntu 21.04

**Comment by arthurwolf** [comment]
I just tried again (both .deb and Appimage) with 0.12, and got the exact same problems.

I'd really like to use this. What can I do to fix these problems???

**Comment by lencx** [comment]
You can try to upgrade Ubuntu to the latest version.

**Comment by arthurwolf** [comment]
I can't upgrade Ubuntu versions no, that would be a massive endeavor, and very risky...

Is there any other way I can get this to work?

**Comment by lencx** [comment]
> Is there any other way I can get this to work?

You can clone the project locally, then check the https://tauri.app/ documentation to build it yourself.

**Comment by arthurwolf** [comment]
> > Is there any other way I can get this to work?
> 
> You can clone the project locally, then check the https://tauri.app/ documentation to build it yourself.

You can see in the issue original comment, the third method I tried is "building" following the instructions in the Readme, and that *also* produces an error (a different one)

**Comment by lencx** [comment]
Provide node.js and rust version information.

**Comment by LJM2018** [comment]
The same thing happened to me. Since the V0.10.3( the last usable version), I cannot run it in Ubuntu 20.04. I tried  deb, appimage, yarn but got the exact same errors. 

rustc 1.61.0
nodejs v10.19.0

**Comment by LJM2018** [comment]
![image](https://user-images.githubusercontent.com/35580709/223648332-5f510a9a-2c2c-493c-9d32-5660efd19aec.png)

**Comment by lencx** [comment]
Please upgrade the node.js version (e.g. `v18.15.0`).

**Comment by LJM2018** [comment]
> Please upgrade the node.js version (e.g. `v18.15.0`).

![image](https://user-images.githubusercontent.com/35580709/223668738-7956c5ea-5a12-4380-8250-c28f96533ad6.png)

Seems like the problem remains lol

**Comment by laraconda** [comment]
I ran into the same problem in Debian 11.
