### ISSUE TITLE
[Bug] Application error: a client-side exception has occurred 

### ISSUE THREAD

**Issue by icefed** [lencx/ChatGPT#526]
### Version

0.11.0

### Bug description

click a `New chat` session, get an error.

<img width="682" alt="image" src="https://user-images.githubusercontent.com/3964419/221764711-61aa66f6-2c70-4517-a817-32b81b6e5eed.png">

<img width="800" alt="image" src="https://user-images.githubusercontent.com/3964419/221764732-8f30cf48-b279-4ab2-b4e2-b07992b22dee.png">

### OS

macos 12.5.1

**Comment by Byc4i** [comment]
_app-dedfe8ecfffebe40.js:7 
        
       TypeError: Cannot read properties of undefined (reading 'parentId')
    at [[...chatId]]-c18e9cd293a366ce.js:1:32753
    at Object.useMemo (framework-7a789ee31d2a7534.js:9:67915)
    at n.useMemo (framework-7a789ee31d2a7534.js:25:5985)
    at [[...chatId]]-c18e9cd293a366ce.js:1:32685
    at aD (framework-7a789ee31d2a7534.js:9:61585)
    at uz (framework-7a789ee31d2a7534.js:9:73267)
    at uC (framework-7a789ee31d2a7534.js:9:72473)
    at u_ (framework-7a789ee31d2a7534.js:9:72078)
    at i (framework-7a789ee31d2a7534.js:9:123091)
    at o3 (framework-7a789ee31d2a7534.js:9:107168)
    at o1 (framework-7a789ee31d2a7534.js:9:107096)
    at o0 (framework-7a789ee31d2a7534.js:9:106959)
    at oB (framework-7a789ee31d2a7534.js:9:103746)
    at oQ (framework-7a789ee31d2a7534.js:9:104135)
    at lf (framework-7a789ee31d2a7534.js:9:45456)
    at framework-7a789ee31d2a7534.js:9:101678
(匿名) @ _app-dedfe8ecfffebe40.js:7
_app-dedfe8ecfffebe40.js:7 
        
       A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred

**Comment by kabra4** [comment]
i have the same issue
![image](https://user-images.githubusercontent.com/57127182/222045126-bccc264d-250e-48c7-a64e-5dcc4941149a.png)

**Comment by DuomaxAE** [comment]
Are you guys using the "ChatGPT Optimizer - Boost Your AI Workflow" Chrome extension? I had the same issue but when I uninstalled it, ChatGPT worked normally.
